### ISSUE TITLE
Paper ID 213

### ISSUE THREAD

**Issue by yzcjtr** [extreme-assistant/cvpr2019#10]
Hi, Thanks for the repo. While this paper is wrongly labeled with "stereo matching" tag. Actually, it proposes architectures for learning correspondence, and can be applied into both "stereo matching" and "optical flow".

**Comment by extreme-assistant** [comment]
> Hi, Thanks for the repo. While this paper is wrongly labeled with "stereo matching" tag. Actually, it proposes architectures for learning correspondence, and can be applied into both "stereo matching" and "optical flow".

Thanks for reminding , I added another  label(optical flow) for  213 paper.
