### ISSUE TITLE
please add our cvpr'19 paper, thanks very much.

### ISSUE THREAD

**Issue by danieljf24** [extreme-assistant/cvpr2019#13]
Dual Encoding for Zero-Example Video Retrieval
作者：Jianfeng Dong, Xirong Li, Chaoxi Xu, Shouling Ji, Yuan He, Gang Yang and Xun Wang
论文链接：https://arxiv.org/abs/1809.06181 
代码链接：https://github.com/danieljf24/dual_encoding

**Comment by extreme-assistant** [comment]
> Dual Encoding for Zero-Example Video Retrieval
> 作者：Jianfeng Dong, Xirong Li, Chaoxi Xu, Shouling Ji, Yuan He, Gang Yang and Xun Wang
> 论文链接：[https://arxiv.org/abs/1809.06181 ](https://arxiv.org/abs/1809.06181%C2%A0)
> 代码链接：https://github.com/danieljf24/dual_encoding

Added.
