### ISSUE TITLE
Please add our cvpr'19 paper (0080), thanks very much.

### ISSUE THREAD

**Issue by D-X-Y** [extreme-assistant/cvpr2019#14]
Searching for A Robust Neural Architecture in Four GPU Hours
作者：Xuanyi Dong, Yi Yang
代码链接：https://github.com/D-X-Y/GDAS (will be public soon)

**Comment by sebgao** [comment]
Any arxiv links? Very interested about it.

**Comment by extreme-assistant** [comment]
> Searching for A Robust Neural Architecture in Four GPU Hours
> 作者：Xuanyi Dong, Yi Yang
> 代码链接：https://github.com/D-X-Y/GDAS (will be public soon)

Added.

**Comment by D-X-Y** [comment]
@sebgao Thanks for your interest, we will public it in about one month~

**Comment by D-X-Y** [comment]
> > Searching for A Robust Neural Architecture in Four GPU Hours
> > 作者：Xuanyi Dong, Yi Yang
> > 代码链接：https://github.com/D-X-Y/GDAS (will be public soon)
> 
> Added.

Thanks a lot.

**Comment by D-X-Y** [comment]
@extreme-assistant Hi, we just make the codes publicly available. Would you mind to remove the "will be public soon" in the readme? Thanks a lot.

**Comment by D-X-Y** [comment]
@extreme-assistant Hi Would you mind to update the information of your paper?

Searching for A Robust Neural Architecture in Four GPU Hours
作者：Xuanyi Dong, Yi Yang
代码链接：https://github.com/D-X-Y/GDAS
论文链接：https://github.com/D-X-Y/GDAS/blob/master/data/GDAS.pdf
