### ISSUE TITLE
Wrong Author List of Paper 121

### ISSUE THREAD

**Issue by WellyZhang** [extreme-assistant/cvpr2019#16]
Thanks very much for creating this archive and listing our paper.

However, author list of Paper 121 RAVEN: A Dataset for Relational and Analogical Visual rEasoNing is wrong.

It should be: Chi Zhang, Feng Gao, Baoxiong Jia, Yixin Zhu, Song-Chun Zhu

**Comment by tirtadharma** [comment]
Auhshhshhs

**Comment by tirtadharma** [comment]
Ll

**Comment by extreme-assistant** [comment]
> Thanks very much for creating this archive and listing our paper.
> 
> However, author list of Paper 121 RAVEN: A Dataset for Relational and Analogical Visual rEasoNing is wrong.
> 
> It should be: Chi Zhang, Feng Gao, Baoxiong Jia, Yixin Zhu, Song-Chun Zhu

Thanks for reminding. Corrected.
