### ISSUE TITLE
Please add our paper. Thanks.

### ISSUE THREAD

**Issue by wenguanwang** [extreme-assistant/cvpr2019#22]
code & paper: https://github.com/wenguanwang/AGS

#Learning Unsupervised Video Primary Object Segmentation through Visual Attention (CVPR19)

Wenguan Wang, Hongmei Song, Shuyang Zhao, Jianbing Shen, Sanyuan Zhao, Steven Chu Hong Hoi, and Haibin Ling

additional link to the paper: http://www.dabi.temple.edu/~hbling/publication/UVOS-cvpr19.pdf

**Comment by extreme-assistant** [comment]
> code & paper: https://github.com/wenguanwang/AGS
> 
> #Learning Unsupervised Video Primary Object Segmentation through Visual Attention (CVPR19)
> 
> Wenguan Wang, Hongmei Song, Shuyang Zhao, Jianbing Shen, Sanyuan Zhao, Steven Chu Hong Hoi, and Haibin Ling
> 
> additional link to the paper: http://www.dabi.temple.edu/~hbling/publication/UVOS-cvpr19.pdf

Added, No. 533
