### ISSUE TITLE
Bag of Tricks for Image Classification with Convolutional Neural Networks

### ISSUE THREAD

**Issue by hetong007** [extreme-assistant/cvpr2019#6]
Please add this one: https://arxiv.org/abs/1812.01187
author: Tong He, Zhi Zhang, Hang Zhang, Zhongyue Zhang, Junyuan Xie, Mu Li
code: https://github.com/dmlc/gluon-cv

Thanks!

**Comment by extreme-assistant** [comment]
> Please add this one: https://arxiv.org/abs/1812.01187
> author: Tong He, Zhi Zhang, Hang Zhang, Zhongyue Zhang, Junyuan Xie, Mu Li
> code: https://github.com/dmlc/gluon-cv
> 
> Thanks!

Added.
