### ISSUE TITLE
For Paper id 101

### ISSUE THREAD

**Issue by LinZhuoChen** [extreme-assistant/cvpr2019#8]
I hope you can note that the code of paper id 101:Decoders Matter for Semantic Segmentation: Data-Dependent Decoding Enables Flexible Feature Aggregation, is implemented unofficially. Thank you very much.

**Comment by extreme-assistant** [comment]
> I hope you can note that the code of paper id 101:Decoders Matter for Semantic Segmentation: Data-Dependent Decoding Enables Flexible Feature Aggregation, is implemented unofficially. Thank you very much.

Thanks , I added a note for the paper.
